version: '3.9'

services:
  streamlit-app:
    image: st125050/a3car:latest  # Replace with your actual Docker image name
    build:
      context: .
      dockerfile: Dockerfile  # Assuming your Dockerfile is named 'Dockerfile'
    ports:
      - "8505:8505"
    environment:
      - HOST=0.0.0.0
      - PORT=8505
    labels:
      # Allow Traefik to talk with your service
      - traefik.enable=true
      # Tell Traefik to use port 8505
      - traefik.http.services.streamlit-app.loadbalancer.server.port=8505
      # This configures your domain name
      - traefik.http.routers.streamlit-app.rule=Host(`app3.st125050.ml.brain.cs.ait.ac.th`)  # Ensure this domain matches your DNS settings
      # Enable SSL
      - traefik.http.routers.streamlit-app.tls=true
      - traefik.http.routers.streamlit-app.tls.certresolver=production
      - traefik.http.routers.streamlit-app.entrypoints=websecure
    networks:
      - default
      - traefik_default

networks:
  default:
  traefik_default:
    external: true
